# Generated by Django 3.2.9 on 2022-11-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('celular', models.CharField(max_length=10, unique=True, verbose_name='Celular')),
                ('apellidos', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=25, unique=True, verbose_name='Cedula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del usuario')),
                ('administrador', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
