# Generated by Django 4.1.3 on 2022-12-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0003_centro_operacion_compañia_item_nomina_proveedor"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="centro_operacion", table="centros_de_pperaciones",
        ),
        migrations.AlterModelTable(name="compañia", table="compania",),
        migrations.AlterModelTable(name="nomina", table="Nomina",),
        migrations.AlterModelTable(name="proveedor", table="proovedores",),
    ]
