# Generated by Django 4.1.3 on 2022-12-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0004_alter_centro_operacion_table_alter_compañia_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="nomina", table="nomina",),
    ]
