# Generated by Django 4.1.3 on 2022-12-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0005_alter_nomina_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centro_operacion",
            name="nombre_proyecto",
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="compañia",
            name="compañia",
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="nomina",
            name="cargo",
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="nomina",
            name="razon_social",
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nit",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="razon_social",
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
