# Generated by Django 4.1.3 on 2022-12-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0008_centro_operacion_id_proyecto"),
    ]

    operations = [
        migrations.RenameModel(old_name="Compañia", new_name="Compania",),
        migrations.RenameField(
            model_name="compania", old_name="compañia", new_name="compania",
        ),
    ]
