# Generated by Django 4.1.3 on 2022-12-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0009_rename_compañia_compania_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="compania", table="companias",),
        migrations.AlterModelTable(name="nomina", table="nominas",),
    ]
