# Generated by Django 4.1.3 on 2022-12-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0010_alter_compania_table_alter_nomina_table"),
    ]

    operations = [
        migrations.DeleteModel(name="Proveedor",),
    ]
