# Generated by Django 4.1.3 on 2022-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0011_delete_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "razon_social",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={"db_table": "proovedores",},
        ),
    ]
