# Generated by Django 4.1.3 on 2022-12-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0013_alter_proveedor_razon_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centro_Operacion',
        ),
        migrations.DeleteModel(
            name='Compania',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Nomina',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
