# Generated by Django 3.2.9 on 2022-12-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0002_auto_20221214_1454'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
