# Generated by Django 4.1.3 on 2022-12-14 21:56

import ModSubcontratos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0003_alter_item_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poliza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_poliza", models.CharField(max_length=23)),
                ("numero_poliza", models.CharField(max_length=100)),
                ("aseguradora", models.CharField(max_length=34)),
                ("fecha_vencimiento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Subcontrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("1", "1.1 Contratos con IVA pleno suministros."),
                            ("2", "1.2 Contratos con IVA pleno y algunos servicios."),
                            ("3", "2. Contratos de servicios de obra civil."),
                            ("4", "3. Contratos mixtos."),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "tipo_orden",
                    models.CharField(
                        choices=[("1", "OCS"), ("2", "OCM")], max_length=5
                    ),
                ),
                ("numero_orden", models.CharField(max_length=250)),
                ("tarifa_iva", models.IntegerField(default=19)),
                ("porcentaje_administracion", models.IntegerField(default=0)),
                ("porcentaje_imprevistos", models.IntegerField(default=0)),
                ("porcentaje_utilidad", models.IntegerField(default=0)),
                (
                    "seguimiento_acta",
                    models.CharField(
                        choices=[
                            ("1", "Semanal"),
                            ("2", "Catorcenal"),
                            ("3", "Quincenal"),
                            ("4", "Mensual"),
                        ],
                        max_length=5,
                    ),
                ),
                ("fecha_inicio_contrato", models.DateField()),
                ("fecha_vencimiento_contrato", models.DateField()),
                ("director_obra", models.CharField(max_length=250)),
                ("gestor_contrato", models.CharField(max_length=250)),
                ("correo_notificacion_proveedor", models.EmailField(max_length=254)),
                (
                    "validadores",
                    models.CharField(
                        choices=[
                            ("Ambiental", "Ambiental"),
                            ("Social", "Social"),
                            ("RRHH", "RRHH"),
                            ("Calidad", "Calidad"),
                            ("SST", "SST"),
                            ("P&C Planeación", "P&C Planeación"),
                            ("P&C Costos", "P&C Costos"),
                            ("Administrador", "Administrador"),
                            ("Seguros", "Seguros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contrato",
                    models.FileField(
                        upload_to=ModSubcontratos.models.guardar_contrato,
                        validators=[ModSubcontratos.models.validar_extencion_archivo],
                    ),
                ),
                (
                    "polizas_garantias",
                    models.FileField(
                        upload_to=ModSubcontratos.models.guardar_polizas_garantias,
                        validators=[ModSubcontratos.models.validar_extencion_archivo],
                    ),
                ),
                (
                    "acta_inicio",
                    models.FileField(
                        upload_to=ModSubcontratos.models.guardar_acta_inicio,
                        validators=[ModSubcontratos.models.validar_extencion_archivo],
                    ),
                ),
                (
                    "modificaciones_contractuales",
                    models.FileField(
                        upload_to=ModSubcontratos.models.guardar_modificaciones_contractuales,
                        validators=[ModSubcontratos.models.validar_extencion_archivo],
                    ),
                ),
                (
                    "acta_recibo_final",
                    models.FileField(
                        upload_to=ModSubcontratos.models.guardar_acta_recibo_final,
                        validators=[ModSubcontratos.models.validar_extencion_archivo],
                    ),
                ),
                (
                    "acta_liquidacion",
                    models.FileField(
                        upload_to=ModSubcontratos.models.guardar_acta_liquidacion,
                        validators=[ModSubcontratos.models.validar_extencion_archivo],
                    ),
                ),
                (
                    "elaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ModSubcontratos.nomina",
                    ),
                ),
                ("polizas", models.ManyToManyField(to="ModSubcontratos.poliza")),
                (
                    "proveedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ModSubcontratos.proveedor",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ModSubcontratos.centro_operacion",
                    ),
                ),
            ],
        ),
    ]
