# Generated by Django 4.1.3 on 2022-12-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0005_alter_subcontrato_validadores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontrato",
            name="tipo_contrato",
            field=models.CharField(
                choices=[
                    ("1.1", "1.1 Contratos con IVA pleno suministros."),
                    ("1.2", "1.2 Contratos con IVA pleno y algunos servicios."),
                    ("3", "2. Contratos de servicios de obra civil."),
                    ("4", "3. Contratos mixtos."),
                ],
                max_length=5,
            ),
        ),
    ]
