# Generated by Django 4.1.3 on 2022-12-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0006_alter_subcontrato_tipo_contrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontrato",
            name="tipo_contrato",
            field=models.CharField(
                choices=[
                    ("1.1", "1.1 Contratos con IVA pleno suministros."),
                    ("1.2", "1.2 Contratos con IVA pleno y algunos servicios."),
                    ("2", "2. Contratos de servicios de obra civil."),
                    ("3", "3. Contratos mixtos."),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterModelTable(name="poliza", table="polizas",),
        migrations.AlterModelTable(name="subcontrato", table="subcontratos",),
    ]
