# Generated by Django 4.1.3 on 2022-12-15 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0008_subcontrato_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontrato",
            name="compania",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ModSubcontratos.compania",
            ),
        ),
    ]
