# Generated by Django 3.2.9 on 2022-12-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0009_subcontrato_compania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Subcontrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.IntegerField()),
                ('item_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModSubcontratos.item')),
                ('subcontrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModSubcontratos.subcontrato')),
            ],
            options={
                'db_table': 'items_subcontrato',
            },
        ),
    ]
