# Generated by Django 4.1.3 on 2022-12-19 16:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0011_item_subcontrato_unidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontrato",
            name="validadores",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Ambiental", "Ambiental"),
                    ("Social", "Social"),
                    ("RRHH", "RRHH"),
                    ("Calidad", "Calidad"),
                    ("SST", "SST"),
                    ("P&C Planeación", "P&C Planeación"),
                    ("P&C Costos", "P&C Costos"),
                    ("Administrador", "Administrador"),
                    ("Seguros", "Seguros"),
                ],
                max_length=150,
            ),
        ),
    ]
