# Generated by Django 4.1.3 on 2022-12-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0013_subcontrato_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontrato",
            name="proximo_envio_correo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
