# Generated by Django 3.2.9 on 2022-12-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0014_alter_subcontrato_proximo_envio_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='aseguradora',
            field=models.CharField(choices=[('1', 'SBS Seguros Colombia S.A'), ('2', 'BBVA Seguros'), ('3', 'CHUBB'), ('4', 'HDI Seguros S.A'), ('5', 'La Previsora'), ('6', 'BMI'), ('7', 'Suramericana S.A'), ('8', 'AXA Colpatria'), ('9', 'Berkley Seguros'), ('10', 'Confianza S.A'), ('11', 'Colmena Seguros'), ('12', 'Liberty Seguros'), ('13', 'Segurexpo'), ('14', 'Seguros del Estado'), ('15', 'Nacionar del seguros'), ('16', 'Zurich'), ('17', 'Aseguradora Solidaria'), ('18', 'Jmalucelli Travelers Seguros S.A'), ('19', 'Seguros Bolívar'), ('20', 'Seguros Mundial'), ('21', 'La Equidad Seguros')], max_length=34),
        ),
    ]
