# Generated by Django 3.2.9 on 2022-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0015_alter_poliza_aseguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontrato',
            name='consecutivo',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcontrato',
            name='impo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
