# Generated by Django 3.2.9 on 2022-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0016_auto_20221224_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontrato',
            name='estado',
            field=models.CharField(choices=[('1', 'En ejecución'), ('2', 'No ejecutado'), ('3', 'Suspendido'), ('4', 'Liquidado')], default='1', max_length=30),
        ),
    ]
