# Generated by Django 3.2.9 on 2022-12-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0017_alter_subcontrato_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontrato',
            name='consecutivo',
        ),
        migrations.RemoveField(
            model_name='subcontrato',
            name='impo',
        ),
    ]
