# Generated by Django 3.2.9 on 2022-12-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0019_auto_20221224_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontrato',
            name='impo',
        ),
    ]
