# Generated by Django 3.2.9 on 2022-12-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0020_remove_subcontrato_impo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontrato',
            name='impo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
