# Generated by Django 3.2.9 on 2022-12-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0021_subcontrato_impo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontrato',
            name='consecutivo',
            field=models.BigIntegerField(unique=True),
        ),
    ]
