# Generated by Django 4.1.3 on 2022-12-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModSubcontratos', '0022_alter_subcontrato_consecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('subitem', models.ManyToManyField(to='ModSubcontratos.item_subcontrato')),
            ],
        ),
    ]
