# Generated by Django 4.1.3 on 2022-12-27 18:25

import ModSubcontratos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0023_subcapitulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "estdo",
                    models.CharField(
                        choices=[("1", "Sin revisar"), ("2", "Aprobado")], max_length=50
                    ),
                ),
                (
                    "listado_personal",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ModSubcontratos.models.guardar_listado_personal,
                    ),
                ),
                (
                    "seguridad_social",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ModSubcontratos.models.guardar_seguridad_social,
                    ),
                ),
                (
                    "otros_datos_adjuntos",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ModSubcontratos.models.guardar_otros_datos_adjuntos,
                    ),
                ),
                (
                    "firma_Ambiental",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_Ambiental
                    ),
                ),
                (
                    "firma_Social",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_Social
                    ),
                ),
                (
                    "firma_RRHH",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_RRHH
                    ),
                ),
                (
                    "firma_Calidad",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_Calidad
                    ),
                ),
                (
                    "firma_SST",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_SST
                    ),
                ),
                (
                    "firma_Planeacion",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_Planeacion
                    ),
                ),
                (
                    "firma_Costos",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_Costos
                    ),
                ),
                (
                    "firma_Administrador",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_Administrador
                    ),
                ),
                (
                    "firma_Seguros",
                    models.ImageField(
                        upload_to=ModSubcontratos.models.guardar_firma_Seguros
                    ),
                ),
                (
                    "subcontrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ModSubcontratos.subcontrato",
                    ),
                ),
            ],
            options={"db_table": "actas",},
        ),
        migrations.CreateModel(
            name="Paquete_Trabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paquete", models.CharField(max_length=200)),
            ],
            options={"db_table": "paquetes_de_trabajo",},
        ),
        migrations.AlterModelTable(name="proveedor", table="proveedores",),
        migrations.AlterModelTable(name="subcapitulo", table="subcapitulos",),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ModSubcontratos.acta",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ModSubcontratos.item_subcontrato",
                    ),
                ),
                (
                    "paquete_trabajo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ModSubcontratos.paquete_trabajo",
                    ),
                ),
            ],
            options={"db_table": "seguimiento_acta",},
        ),
    ]
