# Generated by Django 4.1.3 on 2022-12-27 18:31

import ModSubcontratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModSubcontratos", "0024_acta_paquete_trabajo_alter_proveedor_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acta",
            name="firma_Administrador",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_Administrador,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_Ambiental",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_Ambiental,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_Calidad",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_Calidad,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_Costos",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_Costos,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_Planeacion",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_Planeacion,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_RRHH",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_RRHH,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_SST",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_SST,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_Seguros",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_Seguros,
            ),
        ),
        migrations.AlterField(
            model_name="acta",
            name="firma_Social",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ModSubcontratos.models.guardar_firma_Social,
            ),
        ),
    ]
